---
version: "2"

services:

    postgres:
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=seismic
            - POSTGRES_PASSWORD=d3v3l0pm3nt!
            - POSTGRES_DB=seismic
        # TODO - Volume

    minio:
        image: minio/minio:latest
        command:
            - server
            - /data
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=dev-TKE8KC10YL
            - MINIO_SECRET_KEY=dev-ALUP1N7WUO

    redis:
        image: redis:3.0
        ports:
            - 6379:6379
